version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - gosec
    - gocritic
    - misspell
    - revive
    - unconvert
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-strings

issues:
  exclude-dirs:
    - gen
  max-issues-per-linter: 0
  max-same-issues: 0
